import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Loader2, FileText, Download, Plus, Printer, QrCode } from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';

export function AdminReceipts() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState('');

  const { data: receipts, isLoading } = useQuery({
    queryKey: ['admin-receipts'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('receipts')
        .select(`
          *,
          orders(
            order_number,
            total_amount,
            status,
            shipping_address,
            profiles:user_id(name, email)
          )
        `)
        .order('generated_at', { ascending: false });
      
      if (error) throw error;
      return data;
    },
  });

  const { data: ordersWithoutReceipts } = useQuery({
    queryKey: ['orders-without-receipts'],
    queryFn: async () => {
      const { data: allOrders, error: ordersError } = await supabase
        .from('orders')
        .select('id, order_number, total_amount, status')
        .in('status', ['delivered', 'shipped', 'in_transit']);
      
      if (ordersError) throw ordersError;

      const { data: existingReceipts, error: receiptsError } = await supabase
        .from('receipts')
        .select('order_id');
      
      if (receiptsError) throw receiptsError;

      const receiptOrderIds = new Set(existingReceipts?.map(r => r.order_id));
      return allOrders?.filter(order => !receiptOrderIds.has(order.id)) || [];
    },
  });

  const generateReceiptMutation = useMutation({
    mutationFn: async (orderId: string) => {
      // Generate a simple QR code data (in real app, this would be a proper QR code)
      const qrCodeData = `ORDER:${orderId}`;
      
      const { error } = await supabase
        .from('receipts')
        .insert({
          order_id: orderId,
          qr_code: qrCodeData,
          receipt_number: '', // Will be auto-generated by trigger
        } as any);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin-receipts'] });
      queryClient.invalidateQueries({ queryKey: ['orders-without-receipts'] });
      toast.success('Receipt generated');
    },
    onError: (error) => {
      toast.error('Failed to generate receipt');
      console.error(error);
    },
  });

  const filteredReceipts = receipts?.filter(receipt => 
    receipt.receipt_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
    receipt.orders?.order_number.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold font-serif">Receipts</h1>
        <Dialog>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              Generate Receipt
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Generate Receipt for Order</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              {ordersWithoutReceipts?.length === 0 ? (
                <p className="text-sm text-muted-foreground text-center py-4">
                  All eligible orders have receipts
                </p>
              ) : (
                <div className="space-y-2">
                  {ordersWithoutReceipts?.map((order) => (
                    <div 
                      key={order.id}
                      className="flex items-center justify-between p-3 border border-border rounded-lg"
                    >
                      <div>
                        <p className="font-medium">{order.order_number}</p>
                        <p className="text-sm text-muted-foreground">
                          GH₵{order.total_amount.toFixed(2)} - {order.status}
                        </p>
                      </div>
                      <Button 
                        size="sm"
                        onClick={() => generateReceiptMutation.mutate(order.id)}
                        disabled={generateReceiptMutation.isPending}
                      >
                        Generate
                      </Button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>All Receipts</CardTitle>
            <Input
              placeholder="Search receipts..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="max-w-xs"
            />
          </div>
        </CardHeader>
        <CardContent>
          {filteredReceipts?.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">
              No receipts found
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Receipt #</TableHead>
                  <TableHead>Order #</TableHead>
                  <TableHead>Customer</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredReceipts?.map((receipt) => (
                  <TableRow key={receipt.id}>
                    <TableCell className="font-mono text-sm">
                      {receipt.receipt_number}
                    </TableCell>
                    <TableCell className="font-mono text-sm">
                      {receipt.orders?.order_number}
                    </TableCell>
                    <TableCell>
                      {(receipt.orders?.profiles as any)?.name || 'Unknown'}
                    </TableCell>
                    <TableCell>
                      GH₵{receipt.orders?.total_amount.toFixed(2)}
                    </TableCell>
                    <TableCell>
                      {format(new Date(receipt.generated_at), 'MMM d, yyyy')}
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-2">
                        <Button variant="outline" size="sm">
                          <Printer className="h-4 w-4 mr-1" />
                          Print
                        </Button>
                        <Button variant="outline" size="sm">
                          <QrCode className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
