// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

export const missingSupabaseEnvVars = [
  !SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
  !SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
].filter((value): value is string => Boolean(value));

export const supabaseConfigError =
  missingSupabaseEnvVars.length > 0
    ? `Missing Supabase environment variables: ${missingSupabaseEnvVars.join(', ')}`
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createUnavailableClient(): SupabaseClient<Database> {
  return new Proxy(
    {},
    {
      get() {
        throw new Error(
          supabaseConfigError ??
            'Supabase client is unavailable because the environment configuration is incomplete.',
        );
      },
    },
  ) as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> = supabaseConfigError
  ? createUnavailableClient()
  : createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
